sudo: true
language: python
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt

branches:
  only:
    - main

addons:
  apt:
    packages:
      - doxygen


script:
  - python3 pipeline_test.py
  - doxygen Doxyfile

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main