install: #which pip packages to install
  - numpy
verbose: True
background: # declare background processes, 
# you can start and stop them in the begin, run or end blocks
  - background1 : monitor.py -> 
instance: #declare class instances and the args to provide their instantiation
  - DefectReport : d 
begin: # begin blocks execute before the pipeline starts running its main workload
  - start : background1 #starts background1 process

run: # run blocks define the main workload
   - check: #can specify run phases like so
    # you can declare concurrent groups of functions to execute like so:
    concurrent:
      - 'analyze workload 1'
      - 'analyze workload 2'
      - 'analyze workload 3'
    
    - some_regular_function #call this function with no arguments
    - some_regular_function_with_args:
      - arg1
      - arg2
      - arg4 = 5
  extract_db2diag.log:
    - d.generateReport
  analyze:
    - d.analyze results
  report:
    - d.dumpReport

end: #end blocks are always executed at the end of the pipeline, even on failure
  - stop background1 # stops background1 process, if not already stopped

http: # can add html requests
  domain:
    - 'localhost:3000'
  phase:
    pass
  pipeline:
    pass

database:
  domain: True
  schema : 'schema name'
  pipeline: True
  
